// === GitHub Types ===

export interface GhLabel {
	name: string;
}

export interface GhIssue {
	number: number;
	title: string;
	body: string;
	labels: GhLabel[];
	assignees: Array<{ login: string }>;
}

// === Run State ===

export type RunStatus = "pending" | "ingested" | "running" | "shipping" | "shipped" | "failed";

export interface RunState {
	// GitHub source
	ghIssueId: number;
	ghRepo: string; // "owner/repo"
	ghTitle: string;
	ghLabels: string[];

	// Seeds mapping
	seedsId: string;

	// Lifecycle
	status: RunStatus;
	error?: string;
	retryable?: boolean;

	// Overstory
	agentName?: string;
	branch?: string;
	mergeBranch?: string;

	// Shipping
	prUrl?: string;
	prNumber?: number;

	// Timestamps
	discoveredAt: string;
	ingestedAt?: string;
	dispatchedAt?: string;
	completedAt?: string;
	shippedAt?: string;
	updatedAt: string;
}

// === Config Types ===

export interface RepoConfig {
	owner: string;
	repo: string;
	labels: string[];
	project_root: string;
}

export interface DaemonConfig {
	version: string;
	repos: RepoConfig[];
	poll_interval_minutes: number;
	daily_cap: number;
	dispatch: {
		capability: string;
		max_concurrent: number;
		monitor_interval_seconds: number;
		run_timeout_minutes: number;
	};
	shipping: {
		auto_push: boolean;
		pr_template: string;
	};
}

// === Budget ===

export interface DailyBudget {
	date: string; // YYYY-MM-DD
	dispatched: number;
	cap: number;
	remaining: number;
}

// === Subprocess Abstraction ===

export interface ExecResult {
	exitCode: number;
	stdout: string;
	stderr: string;
}

export type ExecFn = (cmd: string[], opts?: { cwd?: string }) => Promise<ExecResult>;

// === ov coordinator start --json response ===

export interface CoordinatorStartResult {
	success: boolean;
	command: string;
	agentName: string;
	capability: string;
	tmuxSession: string;
	projectRoot: string;
	pid: number;
	watchdog: boolean;
	monitor: boolean;
}

// === ov coordinator send --json response ===

export interface CoordinatorSendResult {
	success: boolean;
	command: string;
	id: string;
	nudged: boolean;
}

// === sd create --json response ===

export interface SdCreateResult {
	success: boolean;
	command: string;
	id: string;
}

// === sd show --json response ===

export interface SdIssue {
	id: string;
	title: string;
	status: string;
	type?: string;
	priority?: number;
	createdAt: string;
	updatedAt: string;
	reason?: string;
}

// === ov coordinator status --json response ===

export interface CoordinatorStatus {
	success: boolean;
	command: string;
	running: boolean;
	sessionId?: string;
	state?: string;
	tmuxSession?: string;
	pid?: number;
	startedAt?: string;
	lastActivity?: string;
	watchdogRunning: boolean;
	monitorRunning: boolean;
}

// === ov status --json response ===

export interface OvAgentInfo {
	id: string;
	agentName: string;
	capability: string;
	worktreePath: string;
	branchName: string;
	taskId: string;
	tmuxSession: string;
	state: string;
	pid: number;
	parentAgent: string | null;
	depth: number;
	runId: string | null;
	startedAt: string;
	lastActivity: string;
	escalationLevel: number;
	stalledSince: string | null;
	transcriptPath: string | null;
}

export interface OvStatusResult {
	success: boolean;
	command: string;
	currentRunId: string;
	agents: OvAgentInfo[];
}

// === ov coordinator check-complete --json response ===

export interface TriggerResult {
	enabled: boolean;
	met: boolean;
	detail: string;
}

export interface CheckCompleteResult {
	success: boolean;
	command: string;
	complete: boolean;
	triggers: {
		allAgentsDone: TriggerResult;
		taskTrackerEmpty: TriggerResult;
		onShutdownSignal: TriggerResult;
	};
}

// === Constants ===

export const GREENHOUSE_DIR = ".greenhouse";
export const CONFIG_FILE = "config.yaml";
export const DEFAULT_PR_TEMPLATE = `## Greenhouse Auto-PR

This PR was generated by greenhouse from a GitHub issue.

### Changes
<!-- Summarize changes here -->
`;

// === Dispatch ===

export interface DispatchContext {
	seedsTitle: string;
	ghIssueNumber: number;
	ghRepo: string; // "owner/repo"
	ghIssueBody?: string;
	ghLabels?: string[];
}

// === Shipping ===

export interface ShipResult {
	prUrl: string;
	prNumber: number;
}
